In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv('books_4.csv')

In [31]:
df['language_code'].fillna('eng', inplace=True)

In [32]:
print(df['genre'])

0       genre fiction
1       genre fiction
2       genre fiction
3       genre fiction
4       genre fiction
            ...      
1005    genre fiction
1006    genre fiction
1007    genre fiction
1008    genre fiction
1009    genre fiction
Name: genre, Length: 1010, dtype: object


In [33]:
df['genre'] = df['genre'].replace('genre', '', regex=True)

In [34]:
author_encoder = LabelEncoder()
genre_encoder = LabelEncoder()
lng_encoder = LabelEncoder()
author_rating_encoder = LabelEncoder()
book_avg_encoder = LabelEncoder()
df['Author'] = author_encoder.fit_transform(df['Author'])
df['genre'] = genre_encoder.fit_transform(df['genre'])
df['language_code'] = lng_encoder.fit_transform(df['language_code'])
df['Author_Rating'] = author_rating_encoder.fit_transform(df['Author_Rating'])
#df['Book_average_rating'] = book_avg_encoder.fit_transform(df['Book_average_rating'])

In [35]:
df.head

<bound method NDFrame.head of       Publishing Year                                  Book Name  Author  \
0                2005                                       1776     152   
1                2011                           A Monster Calls      508   
2                2004                     The Tale of Despereaux     381   
3                2005       'Salem's Lot The Illustrated Edition     610   
4                2002                                 2nd Chance     282   
...               ...                                        ...     ...   
1005             1991                                   Xenocide     500   
1006             2003          Y: The Last Man, Vol. 1: Unmanned      84   
1007             2001     Year of Wonders: A Novel of the Plague     221   
1008             2008                                    Zeitoun     145   
1009             1974  Zen and the Art of Motorcycle Maintenance     559   

      language_code  Author_Rating  Book_average_rating  

In [36]:
features = ['language_code', 'Author', 'genre', 'Publishing Year', 'Author_Rating', 'units sold']

In [37]:

X = df[features]
Y = df['Book_average_rating']

In [38]:
print("Missing values distribution: ")
print(X.isna().mean())
print('---')
print(Y.isna().mean())
print('---')
print(X.isnull().mean())
print('---')
print(Y.isnull().mean())

Missing values distribution: 
language_code      0.0
Author             0.0
genre              0.0
Publishing Year    0.0
Author_Rating      0.0
units sold         0.0
dtype: float64
---
0.0
---
language_code      0.0
Author             0.0
genre              0.0
Publishing Year    0.0
Author_Rating      0.0
units sold         0.0
dtype: float64
---
0.0


In [39]:
print(X)

      language_code  Author  genre  Publishing Year  Author_Rating  units sold
0                 3     152      0             2005              2         660
1                 3     508      0             2011              0        4671
2                 2     381      0             2004              2        4455
3                 3     610      0             2005              0       30672
4                 3     282      0             2002              0        2862
...             ...     ...    ...              ...            ...         ...
1005              3     500      0             1991              2         285
1006              3      84      0             2003              0       38664
1007              3     221      0             2001              2        6048
1008              3     145      0             2008              0         107
1009              3     559      0             1974              2        3266

[1010 rows x 6 columns]


In [40]:
X = X.values
Y = Y.values

In [41]:
print(X)

[[   3  152    0 2005    2  660]
 [   3  508    0 2011    0 4671]
 [   2  381    0 2004    2 4455]
 ...
 [   3  221    0 2001    2 6048]
 [   3  145    0 2008    0  107]
 [   3  559    0 1974    2 3266]]


In [42]:
# from sklearn.compose import make_column_transformer
# from sklearn.preprocessing import OneHotEncoder

# onhe = OneHotEncoder(handle_unknown='ignore')

# col_trans = make_column_transformer((onhe, [0, 1, 2, 4]),
#     remainder='passthrough')
# X = col_trans.fit_transform(X)

In [43]:
print(X)

[[   3  152    0 2005    2  660]
 [   3  508    0 2011    0 4671]
 [   2  381    0 2004    2 4455]
 ...
 [   3  221    0 2001    2 6048]
 [   3  145    0 2008    0  107]
 [   3  559    0 1974    2 3266]]


In [44]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [45]:
print(X_train.shape)
print(X_test.shape)

(808, 6)
(202, 6)


In [46]:
print(X_test[0])

[    2   391     1  1981     2 47520]


In [47]:
print(Y_train)

[4.3  4.46 3.79 4.15 3.89 3.85 4.02 4.07 4.18 4.24 3.97 3.57 4.1  4.08
 3.65 3.92 4.08 3.64 4.02 3.83 4.16 4.15 4.11 4.29 3.94 4.22 3.8  4.13
 4.18 4.33 4.26 3.96 4.01 3.82 4.04 3.93 4.08 3.86 3.43 4.32 3.81 4.25
 4.34 3.97 3.21 3.62 3.99 3.85 4.05 4.17 4.2  4.07 4.   3.88 4.31 4.53
 4.09 4.13 4.07 4.3  4.   4.05 3.9  3.89 3.92 4.24 3.78 4.09 4.   4.18
 4.16 4.31 4.49 3.82 4.34 4.06 3.9  3.8  4.01 4.28 4.3  3.69 3.98 4.01
 3.99 4.2  4.38 4.35 3.81 4.14 3.85 3.72 4.38 3.95 4.14 3.94 4.13 4.01
 3.97 3.86 4.21 4.33 4.34 4.16 4.09 4.11 4.3  3.73 4.17 3.97 4.14 4.42
 4.2  3.91 3.93 3.98 3.85 3.62 4.22 4.04 4.02 4.16 4.   4.36 3.72 4.27
 4.24 4.1  4.1  4.13 4.11 3.93 4.19 4.27 3.97 3.92 3.98 4.15 3.77 3.91
 4.28 4.32 3.89 4.29 4.16 3.82 3.76 3.7  4.11 3.75 3.99 4.22 4.06 3.84
 4.   4.3  4.18 4.64 4.12 3.84 3.88 3.79 3.92 3.88 4.14 3.81 3.97 4.2
 3.96 4.4  4.   3.96 4.11 3.98 3.64 3.59 4.36 3.98 4.25 4.18 4.05 4.08
 4.14 3.96 4.21 4.08 3.81 3.84 3.41 3.99 3.85 3.75 4.12 4.21 4.1  4.56
 4.02 4

In [48]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

analyze section


In [49]:
y_pred = regressor.predict(X_test)

In [50]:
print(y_pred)

[3.85 3.8  3.92 4.17 4.23 4.16 4.21 3.76 4.18 4.18 3.75 3.91 3.9  4.11
 3.75 3.9  4.07 4.15 3.92 4.23 4.22 4.16 3.93 4.16 4.22 3.91 4.22 3.92
 3.91 3.76 3.92 3.95 4.14 3.91 3.88 3.91 4.21 3.94 3.69 3.92 4.23 3.75
 4.11 3.88 3.85 4.2  3.92 3.76 4.22 4.2  3.84 3.91 3.93 3.72 3.85 4.14
 4.22 3.9  3.9  3.92 3.92 3.92 3.93 4.23 3.93 3.84 4.21 4.22 3.92 4.17
 4.19 3.91 4.23 3.89 4.22 3.9  4.22 3.9  3.9  3.82 3.91 4.18 4.06 3.93
 3.87 3.91 4.15 4.05 4.24 3.9  3.86 3.9  3.88 4.14 4.21 4.14 3.91 3.85
 3.94 3.91 3.84 3.9  3.91 3.91 3.87 3.91 3.92 4.22 3.92 3.71 3.91 3.91
 4.2  4.21 4.22 4.06 3.92 3.91 4.18 3.87 4.18 4.22 3.94 3.93 3.88 3.91
 4.21 3.93 4.21 4.21 3.91 3.83 3.91 3.84 4.24 4.21 3.92 3.93 4.23 4.21
 3.91 4.21 4.07 3.84 3.92 3.92 3.92 4.23 3.9  3.9  3.83 4.23 3.89 3.91
 3.84 4.17 3.91 3.76 4.21 3.94 3.85 3.91 4.17 4.16 3.91 3.87 3.93 3.92
 3.92 3.91 3.85 3.91 3.92 4.22 4.17 4.21 3.93 3.9  4.24 4.22 3.89 3.93
 3.93 4.15 4.22 3.88 3.82 3.91 3.92 3.91 3.91 4.23 4.16 3.93 3.92 4.24
 3.93 

In [51]:
#print(encoder.inverse_transform(y_pred))

In [52]:
# Predicting the Test set results
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))


[[3.85 3.85]
 [3.8  3.23]
 [3.92 4.25]
 [4.17 4.26]
 [4.23 4.03]
 [4.16 4.04]
 [4.21 4.36]
 [3.76 3.42]
 [4.18 4.21]
 [4.18 4.17]
 [3.75 3.48]
 [3.91 3.67]
 [3.9  3.84]
 [4.11 4.13]
 [3.75 3.37]
 [3.9  3.56]
 [4.07 4.41]
 [4.15 4.04]
 [3.92 4.19]
 [4.23 4.17]
 [4.22 4.16]
 [4.16 4.08]
 [3.93 3.89]
 [4.16 4.23]
 [4.22 4.31]
 [3.91 3.95]
 [4.22 4.14]
 [3.92 4.19]
 [3.91 3.96]
 [3.76 3.31]
 [3.92 3.85]
 [3.95 4.29]
 [4.14 4.22]
 [3.91 3.9 ]
 [3.88 4.05]
 [3.91 3.81]
 [4.21 4.03]
 [3.94 3.62]
 [3.69 3.49]
 [3.92 3.88]
 [4.23 4.26]
 [3.75 3.33]
 [4.11 4.05]
 [3.88 3.86]
 [3.85 3.98]
 [4.2  4.28]
 [3.92 3.83]
 [3.76 3.22]
 [4.22 4.12]
 [4.2  4.18]
 [3.84 3.9 ]
 [3.91 3.69]
 [3.93 3.91]
 [3.72 3.3 ]
 [3.85 3.74]
 [4.14 4.18]
 [4.22 4.34]
 [3.9  3.79]
 [3.9  3.82]
 [3.92 3.99]
 [3.92 3.8 ]
 [3.92 3.92]
 [3.93 3.91]
 [4.23 4.08]
 [3.93 4.14]
 [3.84 3.77]
 [4.21 4.07]
 [4.22 4.07]
 [3.92 4.23]
 [4.17 4.34]
 [4.19 4.15]
 [3.91 4.14]
 [4.23 4.05]
 [3.89 3.51]
 [4.22 4.04]
 [3.9  4.07]
 [4.22 4.14]

In [53]:
from sklearn.metrics import r2_score
Accuracy=r2_score(Y_test, y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy)


 Accuracy of the model is 48.43


In [54]:
#predict user input
user_input = ['en-US', 'Christopher Moore', 'nonfiction', 2005, 'Intermediate', 960]

user_input[0] = lng_encoder.transform([user_input[0]])[0]
user_input[1] = author_encoder.transform([user_input[1]])[0]
user_input[2] = genre_encoder.transform([user_input[2]])[0]
user_input[4] = author_rating_encoder.transform([user_input[4]])[0]
print(user_input)
#df['Book_average_rating'] = book_avg_encoder.fit_transform(df['Book_average_rating'])
pred_user_input = regressor.predict([user_input])
print(pred_user_input)

[2, 120, 3, 2005, 2, 960]
[3.94]
